### ISSUE TITLE
How execute this code?

### ISSUE THREAD

**Issue by msmtech-maker** [MrStack/PSO_FCM#1]
Hello
Can you tell me how can I run psoSearchSeismic?
What parameters?

**Comment by MrStack** [comment]
Hi,
The first parameter is the normalized seismic dataset. It's an m*n matrix.
The second parameter is the fitness function you designed.
The third parameter is the number of particles, the population of PSO.
The fourth parameter is the domain of your fitness function. The format has been described in the file.
Parameters(w,c1,c2) of PSO should be pass to the last parameter('params') of psoSearchSeismic as a vector.

**Comment by msmtech-maker** [comment]
Thanks.

**Comment by msmtech-maker** [comment]
Hi again
Is there any paper related to this repo?
I can not understand some principals...

**Comment by MrStack** [comment]
Hi,
This is a semifinished repo.
Some of these scripts are temporary scripts. They are not maintained well.
If you want to know a more general implementation of PSO, please see my newly uploaded file 'psoSearch.m'. It's similar to 'psoSearchSeismic.m'.

Or a better implementation of MATLAB:
https://www.mathworks.com/help/gads/particleswarm.html?s_tid=srchtitle
Theory:
https://www.mathworks.com/help/gads/particle-swarm-optimization-algorithm.html
There are some references about PSO at the bottom of this page.

And, the FCM algorithm, please refer to:
Bezdek J C , Ehrlich R , Full W . FCM: The fuzzy c-means clustering algorithm[J]. Computers & Geosciences, 1984, 10(2-3):191-203.

**Comment by msmtech-maker** [comment]
Thank you man.
